server.port: 9098
spring.data.mongodb.host: ${MONGO_HOST}
spring.data.mongodb.port: 27017
spring.data.mongodb.database: quotationDB
eureka.client.serviceUrl.defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
spring.application.name: quotation-service
server.servlet.context-path: /quotation-service
rule.code: R1
eureka:
  instance:
    preferIpAddress: true